#!/usr/bin/env node
/** Build icons.svg - an SVG sprite of just the Lucide icons this UI uses.
 *
 * Vendored rather than loaded from a CDN for two reasons: the review UI must
 * work on the LAN with no internet, and a page displaying scanned personal
 * documents should not be issuing third-party requests.
 *
 * Run after changing ICONS:  node build-icons.js
 */
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'node_modules', 'lucide-static', 'icons');
const OUT = path.join(__dirname, 'icons.svg');

// id in the sprite -> lucide icon name
const ICONS = {
  undo: 'undo-2',
  peek: 'expand',
  accept: 'check',
  reject: 'x',
  rotate: 'rotate-cw',
  swap: 'flip-horizontal-2',
  crop: 'crop',
  straighten: 'ruler',
  grid: 'grid-2x2',
  reset: 'rotate-ccw',
  send: 'send-horizontal',
  minus: 'minus',
  plus: 'plus',
};

const symbols = Object.entries(ICONS).map(([id, name]) => {
  const file = path.join(SRC, name + '.svg');
  if (!fs.existsSync(file)) throw new Error(`no such lucide icon: ${name}`);
  const svg = fs.readFileSync(file, 'utf8');
  const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
  // The attributes must live on the SYMBOL: <use> clones the symbol's subtree,
  // so anything set on the sprite's root <svg> is left behind and the icon
  // falls back to fill:black / stroke:none - a solid blob.
  return `  <symbol id="${id}" viewBox="0 0 24 24" fill="none" stroke="currentColor"\n` +
         `          stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\n` +
         `    ${body}\n  </symbol>`;
}).join('\n');

fs.writeFileSync(OUT,
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- Generated by build-icons.js from lucide-static (ISC). Do not edit. -->\n` +
  `<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor"\n` +
  `     stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\n` +
  `${symbols}\n</svg>\n`);

console.log(`icons.svg: ${Object.keys(ICONS).length} symbols, ` +
            `${fs.statSync(OUT).size} bytes`);
